spin_manifest_version = 2

[application]
authors = ["David Justice <david@devigned.com>"]
description = ""
name = "future"
version = "0.1.0"

[[trigger.http]]
route = "/ts"
component = "future"

[component.future]
source = "target/future.wasm"
exclude_files = ["**/node_modules"]
[component.future.build]
command = "npm run build"
